{
    "title": "C# 简单应用", 
    "description": "", 
    "followers": [
        "https://www.zhihu.com/people/MacForce", 
        "https://www.zhihu.com/people/ya-sen-7", 
        "https://www.zhihu.com/people/wu-di-94-62-98", 
        "https://www.zhihu.com/people/xiezhiije", 
        "https://www.zhihu.com/people/yang-cheng-kun-86", 
        "https://www.zhihu.com/people/alive-just", 
        "https://www.zhihu.com/people/xiao-wyao-yao-da", 
        "https://www.zhihu.com/people/yun-yin-81-1", 
        "https://www.zhihu.com/people/kan-bu-tou-ren-xin-52", 
        "https://www.zhihu.com/people/fei-xie-83-40", 
        "https://www.zhihu.com/people/tang-meng-95", 
        "https://www.zhihu.com/people/bailey-43", 
        "https://www.zhihu.com/people/chen-jun-li-90", 
        "https://www.zhihu.com/people/xian-yuan-tang-zhu-ren", 
        "https://www.zhihu.com/people/chl-48-26", 
        "https://www.zhihu.com/people/shbfeng", 
        "https://www.zhihu.com/people/lytry1064", 
        "https://www.zhihu.com/people/hanxu5760", 
        "https://www.zhihu.com/people/zhu-di-you-you", 
        "https://www.zhihu.com/people/cr7h", 
        "https://www.zhihu.com/people/xiong-bo-shi-mian-hua-tang", 
        "https://www.zhihu.com/people/mi-mang-de-lu-ren-85", 
        "https://www.zhihu.com/people/wang-zhen-xiao-hao", 
        "https://www.zhihu.com/people/xudongz", 
        "https://www.zhihu.com/people/zhang-ting-70-6-66", 
        "https://www.zhihu.com/people/dong-shuai-68-28-20", 
        "https://www.zhihu.com/people/liu-yu-jian-84", 
        "https://www.zhihu.com/people/xiao-bing-16-56", 
        "https://www.zhihu.com/people/hao-tian-26-36", 
        "https://www.zhihu.com/people/kong-kong-de-nao-dai-75", 
        "https://www.zhihu.com/people/watersp3", 
        "https://www.zhihu.com/people/ff-ff-68-1", 
        "https://www.zhihu.com/people/qi-cai-lei-3", 
        "https://www.zhihu.com/people/itxiao-sheng-53", 
        "https://www.zhihu.com/people/kasama1981", 
        "https://www.zhihu.com/people/wen-zhi-hong", 
        "https://www.zhihu.com/people/castiel-zhao", 
        "https://www.zhihu.com/people/qing-wen-15-63-10", 
        "https://www.zhihu.com/people/qing-qing-1994", 
        "https://www.zhihu.com/people/bie-qi-ma-yi", 
        "https://www.zhihu.com/people/zhang-xiong-46-98"
    ], 
    "article": [
        {
            "url": "https://zhuanlan.zhihu.com/p/35052524", 
            "userName": "大非sb", 
            "userLink": "https://www.zhihu.com/people/9c5ffb79f07bb76c93142898396dcb04", 
            "upvote": 2, 
            "title": "C#基础知识-用记事本写一个Winform程序", 
            "content": "<p><b>目标：</b>不使用Visual Studio 拖控件的方式，只用系统自带的记事本完成一个简单的winform程序，实现带一个button按钮的窗体，单击button，关闭窗体；</p><p><b>思路：</b></p><p>1.win7以上版本，在电脑C:\\Windows\\<a href=\"https://link.zhihu.com/?target=http%3A//Microsoft.NET\" class=\" wrap external\" target=\"_blank\" rel=\"nofollow noreferrer\">Microsoft.NET</a>\\Framework 里选择对应的.net版本下的文件夹，其中有一个csc.exe的程序，它可以将后缀.cs的源代码编译成可执行程序。</p><p>2.我们知道C#的窗体就是一个继承至Forms的类，Forms类已经封装了窗体的很多基础功能，</p><p>所以我们的代码其实特别简单。</p><p><b>实现方法：</b></p><p>第一步：引入基础的命名空间</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"k\">using</span> <span class=\"nn\">System</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Windows.Forms</span><span class=\"p\">;</span><span class=\"c1\">//窗体\n</span><span class=\"c1\"></span><span class=\"k\">using</span> <span class=\"nn\">System.Drawing</span><span class=\"c1\">//绘图\n</span></code></pre></div><p>第二步：新建一个窗体类Form1继承Form，并定义一个Button，为button设置简单的布局，绑定按钮的点击事件；</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Form1</span><span class=\"p\">:</span><span class=\"n\">Form</span>\n<span class=\"p\">{</span>\n\t<span class=\"k\">private</span> <span class=\"n\">Button</span> <span class=\"n\">btn</span><span class=\"p\">;</span>\n\t<span class=\"k\">public</span> <span class=\"n\">Form1</span><span class=\"p\">()</span>\n\t<span class=\"p\">{</span>   \n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">Text</span><span class=\"p\">=</span><span class=\"s\">&#34;测试窗体&#34;</span><span class=\"p\">;</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">=</span><span class=\"k\">new</span> <span class=\"n\">Button</span><span class=\"p\">();</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">SuspendLayout</span><span class=\"p\">();</span><span class=\"c1\">//挂起布局\n</span><span class=\"c1\"></span>\t\t<span class=\"c1\">//开始布局\n</span><span class=\"c1\"></span>\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Location</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">Point</span><span class=\"p\">(</span><span class=\"m\">82</span><span class=\"p\">,</span> <span class=\"m\">87</span><span class=\"p\">);</span><span class=\"c1\">//System.Drawing.Point\n</span><span class=\"c1\"></span>                <span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Name</span> <span class=\"p\">=</span> <span class=\"s\">&#34;btn&#34;</span><span class=\"p\">;</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Size</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">Size</span><span class=\"p\">(</span><span class=\"m\">75</span><span class=\"p\">,</span> <span class=\"m\">23</span><span class=\"p\">);</span><span class=\"c1\">//System.Drawing.Size\t\n</span><span class=\"c1\"></span>\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Text</span> <span class=\"p\">=</span> <span class=\"s\">&#34;button&#34;</span><span class=\"p\">;</span>\t\t\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Click</span><span class=\"p\">+=</span><span class=\"k\">new</span> <span class=\"n\">System</span><span class=\"p\">.</span><span class=\"n\">EventHandler</span><span class=\"p\">(</span><span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn_Click</span><span class=\"p\">);</span><span class=\"c1\">//设置单击事件[注1]\t\t\n</span><span class=\"c1\"></span>\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">Controls</span><span class=\"p\">.</span><span class=\"n\">Add</span><span class=\"p\">(</span><span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">);</span><span class=\"c1\">//将按钮添加到窗体控件集\n</span><span class=\"c1\"></span>\t<span class=\"p\">}</span>\n\t<span class=\"k\">private</span> <span class=\"k\">void</span> <span class=\"n\">btn_Click</span><span class=\"p\">(</span><span class=\"kt\">object</span> <span class=\"n\">sender</span><span class=\"p\">,</span><span class=\"n\">EventArgs</span> <span class=\"n\">e</span><span class=\"p\">)</span>\n\t<span class=\"p\">{</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">Close</span><span class=\"p\">();</span>\n\t<span class=\"p\">}</span>\n<span class=\"p\">}</span>\n</code></pre></div><p>第三步：定义程序的入口函数：Main()</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"c1\">//定义程序的入口函数\n</span><span class=\"c1\"></span><span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Program</span>\n<span class=\"p\">{</span>\n\t<span class=\"k\">public</span> <span class=\"k\">static</span> <span class=\"k\">void</span> <span class=\"n\">Main</span><span class=\"p\">()</span>\n\t<span class=\"p\">{</span>\n\t\t<span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">Run</span><span class=\"p\">(</span><span class=\"k\">new</span> <span class=\"n\">Form1</span><span class=\"p\">());</span>\n\t<span class=\"p\">}</span>\n<span class=\"p\">}</span>\n</code></pre></div><p>第四步：将写好的代码文件后缀改为.cs，这里我保存为test.cs，打开CMD命令提示符，按下图指令编译程序。（csc.exe是不能直接点击运行的）</p><figure data-size=\"normal\"><noscript><img src=\"https://pic2.zhimg.com/v2-b24505beaebae9bacc529e301015aa0d_b.jpg\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"815\" data-rawheight=\"530\" class=\"origin_image zh-lightbox-thumb\" width=\"815\" data-original=\"https://pic2.zhimg.com/v2-b24505beaebae9bacc529e301015aa0d_r.jpg\"/></noscript><img src=\"data:image/svg+xml;utf8,&lt;svg xmlns=&#39;http://www.w3.org/2000/svg&#39; width=&#39;815&#39; height=&#39;530&#39;&gt;&lt;/svg&gt;\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"815\" data-rawheight=\"530\" class=\"origin_image zh-lightbox-thumb lazy\" width=\"815\" data-original=\"https://pic2.zhimg.com/v2-b24505beaebae9bacc529e301015aa0d_r.jpg\" data-actualsrc=\"https://pic2.zhimg.com/v2-b24505beaebae9bacc529e301015aa0d_b.jpg\"/></figure><p>最后，打开编译好的EXE程序，效果如下图：</p><figure data-size=\"normal\"><noscript><img src=\"https://pic4.zhimg.com/v2-f3ebcd5dbf70ca8a1448b3e5b1838d33_b.jpg\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"819\" data-rawheight=\"535\" class=\"origin_image zh-lightbox-thumb\" width=\"819\" data-original=\"https://pic4.zhimg.com/v2-f3ebcd5dbf70ca8a1448b3e5b1838d33_r.jpg\"/></noscript><img src=\"data:image/svg+xml;utf8,&lt;svg xmlns=&#39;http://www.w3.org/2000/svg&#39; width=&#39;819&#39; height=&#39;535&#39;&gt;&lt;/svg&gt;\" data-caption=\"\" data-size=\"normal\" data-rawwidth=\"819\" data-rawheight=\"535\" class=\"origin_image zh-lightbox-thumb lazy\" width=\"819\" data-original=\"https://pic4.zhimg.com/v2-f3ebcd5dbf70ca8a1448b3e5b1838d33_r.jpg\" data-actualsrc=\"https://pic4.zhimg.com/v2-f3ebcd5dbf70ca8a1448b3e5b1838d33_b.jpg\"/></figure><p>[注1]：</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Click</span><span class=\"p\">+=</span><span class=\"k\">new</span> <span class=\"n\">System</span><span class=\"p\">.</span><span class=\"n\">EventHandler</span><span class=\"p\">(</span><span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn_Click</span><span class=\"p\">);</span>\n<span class=\"c1\">//设置单击事件[注1]\n</span><span class=\"c1\">//EventHandler是预定义的基础委托，一般控件的事件多用这个。关于委托和事件请关注其他文章\n</span></code></pre></div><p>完整代码如下：</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"k\">using</span> <span class=\"nn\">System</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Windows.Forms</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Drawing</span>\n<span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Form1</span><span class=\"p\">:</span><span class=\"n\">Form</span>\n<span class=\"p\">{</span>\n\t<span class=\"k\">private</span> <span class=\"n\">Button</span> <span class=\"n\">btn</span><span class=\"p\">;</span>\n\t<span class=\"k\">public</span> <span class=\"n\">Form1</span><span class=\"p\">()</span>\n\t<span class=\"p\">{</span>   \n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">Text</span><span class=\"p\">=</span><span class=\"s\">&#34;测试窗体&#34;</span><span class=\"p\">;</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">=</span><span class=\"k\">new</span> <span class=\"n\">Button</span><span class=\"p\">();</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">SuspendLayout</span><span class=\"p\">();</span><span class=\"c1\">//挂起控件的布局\n</span><span class=\"c1\"></span>\t\t<span class=\"c1\">//开始布局\n</span><span class=\"c1\"></span>\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Location</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">Point</span><span class=\"p\">(</span><span class=\"m\">82</span><span class=\"p\">,</span> <span class=\"m\">87</span><span class=\"p\">);</span>\n        <span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Name</span> <span class=\"p\">=</span> <span class=\"s\">&#34;btn&#34;</span><span class=\"p\">;</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Size</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">Size</span><span class=\"p\">(</span><span class=\"m\">75</span><span class=\"p\">,</span> <span class=\"m\">23</span><span class=\"p\">);</span>\t\t\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Text</span> <span class=\"p\">=</span> <span class=\"s\">&#34;button&#34;</span><span class=\"p\">;</span>\t\t\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">.</span><span class=\"n\">Click</span><span class=\"p\">+=</span><span class=\"k\">new</span> <span class=\"n\">System</span><span class=\"p\">.</span><span class=\"n\">EventHandler</span><span class=\"p\">(</span><span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn_Click</span><span class=\"p\">);</span><span class=\"c1\">//设置单击事件[注1]\t\t\n</span><span class=\"c1\"></span>\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">Controls</span><span class=\"p\">.</span><span class=\"n\">Add</span><span class=\"p\">(</span><span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">btn</span><span class=\"p\">);</span><span class=\"c1\">//将按钮添加到窗体控件集\n</span><span class=\"c1\"></span>\t<span class=\"p\">}</span>\n\t<span class=\"k\">private</span> <span class=\"k\">void</span> <span class=\"n\">btn_Click</span><span class=\"p\">(</span><span class=\"kt\">object</span> <span class=\"n\">sender</span><span class=\"p\">,</span><span class=\"n\">EventArgs</span> <span class=\"n\">e</span><span class=\"p\">)</span>\n\t<span class=\"p\">{</span>\n\t\t<span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">Close</span><span class=\"p\">();</span>\n\t<span class=\"p\">}</span>\n<span class=\"p\">}</span>\n<span class=\"c1\">//定义程序的入口函数\n</span><span class=\"c1\"></span><span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Program</span>\n<span class=\"p\">{</span>\n\t<span class=\"k\">public</span> <span class=\"k\">static</span> <span class=\"k\">void</span> <span class=\"n\">Main</span><span class=\"p\">()</span>\n\t<span class=\"p\">{</span>\n\t\t<span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">Run</span><span class=\"p\">(</span><span class=\"k\">new</span> <span class=\"n\">Form1</span><span class=\"p\">());</span>\n\t<span class=\"p\">}</span>\n<span class=\"p\">}</span>\n</code></pre></div><p></p>", 
            "topic": [
                {
                    "tag": "C#", 
                    "tagLink": "https://api.zhihu.com/topics/19590712"
                }
            ], 
            "comments": []
        }, 
        {
            "url": "https://zhuanlan.zhihu.com/p/32526818", 
            "userName": "大非sb", 
            "userLink": "https://www.zhihu.com/people/9c5ffb79f07bb76c93142898396dcb04", 
            "upvote": 1, 
            "title": "AutoCAD.NET 二次开发--AutoCAD 中添加自定义的窗体", 
            "content": "<p><b>1、需求</b>：在CAD中输入指令“aaa”，弹出一个窗体，窗体中有一个选择外部Excel文件的按钮，用来选择要导入的数据源，点击确认按钮后关闭窗体，在命令栏显示导入的数据；</p><p><b>2、思路</b>：新增一个winform窗体，使用ShowModalDialog()函数在CAD中显示；</p><p><b>3、环境</b>：AutoCAD 2008/Office 2010/vs2010</p><p><b>4、步骤</b>：</p><p>第一步：将 <a href=\"https://zhuanlan.zhihu.com/p/32434945\" class=\"internal\">AutoCAD.NET 二次开发--CAD中导入Excel数据</a> 文章中ExcelTools类单独编译成dll，在本项目如添加该dll的引用，实现外部Excel单元格数据的读取；</p><p>注意：测试环境为CAD 2008,<a href=\"https://link.zhihu.com/?target=http%3A//xn--dll-7w2eu41drhdtwbp9l391b1i0d.net/\" class=\" wrap external\" target=\"_blank\" rel=\"nofollow noreferrer\">生成dll时务必选择.NET</a> Framework 3.5框架</p><p>第二步：在项目中添加一个名为 NewForm的窗体，如下图；</p><figure data-size=\"normal\"><noscript><img src=\"https://pic2.zhimg.com/v2-e7a84aa45207ae4d2698da4365a7b845_b.jpg\" data-size=\"normal\" data-rawwidth=\"400\" data-rawheight=\"186\" class=\"content_image\" width=\"400\"/></noscript><img src=\"data:image/svg+xml;utf8,&lt;svg xmlns=&#39;http://www.w3.org/2000/svg&#39; width=&#39;400&#39; height=&#39;186&#39;&gt;&lt;/svg&gt;\" data-size=\"normal\" data-rawwidth=\"400\" data-rawheight=\"186\" class=\"content_image lazy\" width=\"400\" data-actualsrc=\"https://pic2.zhimg.com/v2-e7a84aa45207ae4d2698da4365a7b845_b.jpg\"/><figcaption>NewForm窗体</figcaption></figure><p>第三步: 以ModalDialog 模态的方式在CAD中加载NewForm窗体。&lt;备注1&gt;</p><p>第四步：将数据显示在CAD命令栏中；</p><p class=\"ztext-empty-paragraph\"><br/></p><p>具体代码如下：</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"c1\">//主程序代码\n</span><span class=\"c1\"></span><span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.Runtime</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.ApplicationServices</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.EditorInput</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Windows.Forms</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">CadApp</span> <span class=\"p\">=</span> <span class=\"n\">Autodesk</span><span class=\"p\">.</span><span class=\"n\">AutoCAD</span><span class=\"p\">.</span><span class=\"n\">ApplicationServices</span><span class=\"p\">;</span>\n\n<span class=\"k\">namespace</span> <span class=\"nn\">NewFormInCAD</span>\n<span class=\"p\">{</span>\n    <span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Class1</span>\n    <span class=\"p\">{</span><span class=\"na\">\n</span><span class=\"na\">        [CommandMethod(&#34;aaa&#34;)]</span>\n        <span class=\"k\">public</span> <span class=\"k\">void</span> <span class=\"n\">CteateForm</span><span class=\"p\">()</span>\n        <span class=\"p\">{</span>\n\n            <span class=\"n\">Document</span> <span class=\"n\">doc</span> <span class=\"p\">=</span> <span class=\"n\">CadApp</span><span class=\"p\">.</span><span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">DocumentManager</span><span class=\"p\">.</span><span class=\"n\">MdiActiveDocument</span><span class=\"p\">;</span><span class=\"c1\">//获取当前文档\n</span><span class=\"c1\"></span>            <span class=\"n\">Editor</span> <span class=\"n\">ed</span> <span class=\"p\">=</span> <span class=\"n\">doc</span><span class=\"p\">.</span><span class=\"n\">Editor</span><span class=\"p\">;</span><span class=\"c1\">//当前命令栏\n</span><span class=\"c1\"></span>\n            <span class=\"k\">using</span> <span class=\"p\">(</span><span class=\"n\">NewForm</span> <span class=\"n\">form</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">NewForm</span><span class=\"p\">())</span>\n            <span class=\"p\">{</span>\n                <span class=\"n\">CadApp</span><span class=\"p\">.</span><span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">ShowModalDialog</span><span class=\"p\">(</span><span class=\"n\">form</span><span class=\"p\">);</span><span class=\"c1\">//模态方式显示窗体\n</span><span class=\"c1\"></span>                <span class=\"k\">if</span> <span class=\"p\">(</span><span class=\"n\">form</span><span class=\"p\">.</span><span class=\"n\">DialogResult</span> <span class=\"p\">==</span> <span class=\"n\">DialogResult</span><span class=\"p\">.</span><span class=\"n\">OK</span><span class=\"p\">)</span>\n                <span class=\"p\">{</span>\n                    <span class=\"n\">form</span><span class=\"p\">.</span><span class=\"n\">ShowInTaskbar</span> <span class=\"p\">=</span> <span class=\"k\">false</span><span class=\"p\">;</span>\n                    <span class=\"n\">ed</span><span class=\"p\">.</span><span class=\"n\">WriteMessage</span><span class=\"p\">(</span><span class=\"s\">&#34;读取的数据为：&#34;</span> <span class=\"p\">+</span> <span class=\"n\">form</span><span class=\"p\">.</span><span class=\"n\">ImporData</span><span class=\"p\">);</span>\n                <span class=\"p\">}</span>               \n                \n            <span class=\"p\">}</span>\n        <span class=\"p\">}</span>\n\n    <span class=\"p\">}</span>\n<span class=\"p\">}</span>\n\n<span class=\"c1\">//NewForm代码\n</span><span class=\"c1\"></span><span class=\"k\">using</span> <span class=\"nn\">System</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Collections.Generic</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.ComponentModel</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Data</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Drawing</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Linq</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Text</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Windows.Forms</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">DF.Helper.Common</span><span class=\"p\">;</span>\n\n<span class=\"k\">namespace</span> <span class=\"nn\">NewFormInCAD</span>\n<span class=\"p\">{</span>\n    <span class=\"k\">public</span> <span class=\"k\">partial</span> <span class=\"k\">class</span> <span class=\"nc\">NewForm</span> <span class=\"p\">:</span> <span class=\"n\">Form</span>\n    <span class=\"p\">{</span>\n        <span class=\"kt\">string</span> <span class=\"n\">excelName</span><span class=\"p\">;</span><span class=\"c1\">//表格完整路径\n</span><span class=\"c1\"></span>        <span class=\"kt\">string</span> <span class=\"n\">importData</span><span class=\"p\">;</span><span class=\"c1\">//读取的单元格数据\n</span><span class=\"c1\"></span>        <span class=\"k\">public</span> <span class=\"kt\">string</span> <span class=\"n\">ImporData</span>\n        <span class=\"p\">{</span>\n            <span class=\"k\">set</span> <span class=\"p\">{</span> <span class=\"k\">value</span> <span class=\"p\">=</span> <span class=\"n\">importData</span><span class=\"p\">;</span> <span class=\"p\">}</span>\n            <span class=\"k\">get</span> <span class=\"p\">{</span> <span class=\"k\">return</span> <span class=\"n\">importData</span><span class=\"p\">;</span> <span class=\"p\">}</span>\n        <span class=\"p\">}</span>\n        <span class=\"k\">public</span> <span class=\"n\">NewForm</span><span class=\"p\">()</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">InitializeComponent</span><span class=\"p\">();</span>\n\n        <span class=\"p\">}</span>\n        <span class=\"k\">private</span> <span class=\"k\">void</span> <span class=\"n\">NewForm_Load</span><span class=\"p\">(</span><span class=\"kt\">object</span> <span class=\"n\">sender</span><span class=\"p\">,</span> <span class=\"n\">EventArgs</span> <span class=\"n\">e</span><span class=\"p\">)</span>\n        <span class=\"p\">{</span>\n\n        <span class=\"p\">}</span>\n        <span class=\"c1\">//浏览文件按钮\n</span><span class=\"c1\"></span>        <span class=\"k\">private</span> <span class=\"k\">void</span> <span class=\"n\">button_open_Click</span><span class=\"p\">(</span><span class=\"kt\">object</span> <span class=\"n\">sender</span><span class=\"p\">,</span> <span class=\"n\">EventArgs</span> <span class=\"n\">e</span><span class=\"p\">)</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">OpenFileDialog</span> <span class=\"n\">dialog</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">OpenFileDialog</span><span class=\"p\">();</span><span class=\"c1\">//新增浏览文件对话框\n</span><span class=\"c1\"></span>            <span class=\"n\">dialog</span><span class=\"p\">.</span><span class=\"n\">Filter</span> <span class=\"p\">=</span> <span class=\"s\">&#34;Excel file|*.xls;*.xlsx&#34;</span><span class=\"p\">;</span><span class=\"c1\">//筛选xls,和xlsx文件\n</span><span class=\"c1\"></span>            <span class=\"n\">dialog</span><span class=\"p\">.</span><span class=\"n\">RestoreDirectory</span> <span class=\"p\">=</span> <span class=\"k\">false</span><span class=\"p\">;</span>\n            <span class=\"k\">try</span>\n            <span class=\"p\">{</span>\n                <span class=\"k\">if</span> <span class=\"p\">(</span><span class=\"n\">dialog</span><span class=\"p\">.</span><span class=\"n\">ShowDialog</span><span class=\"p\">()</span> <span class=\"p\">==</span> <span class=\"n\">DialogResult</span><span class=\"p\">.</span><span class=\"n\">OK</span><span class=\"p\">)</span>\n                <span class=\"p\">{</span>\n                    <span class=\"n\">textBox_fileName</span><span class=\"p\">.</span><span class=\"n\">Text</span> <span class=\"p\">=</span> <span class=\"n\">dialog</span><span class=\"p\">.</span><span class=\"n\">FileName</span><span class=\"p\">.</span><span class=\"n\">ToString</span><span class=\"p\">();</span>\n                <span class=\"p\">}</span>\n            <span class=\"p\">}</span>\n            <span class=\"k\">catch</span> <span class=\"p\">(</span><span class=\"n\">Exception</span> <span class=\"n\">ex</span><span class=\"p\">)</span>\n            <span class=\"p\">{</span>\n                <span class=\"n\">MessageBox</span><span class=\"p\">.</span><span class=\"n\">Show</span><span class=\"p\">(</span><span class=\"s\">&#34;打开文件出错：&#34;</span><span class=\"p\">+</span><span class=\"n\">ex</span><span class=\"p\">.</span><span class=\"n\">Message</span><span class=\"p\">);</span>\n            <span class=\"p\">}</span>        \n        <span class=\"p\">}</span>\n        <span class=\"c1\">//确定按钮\n</span><span class=\"c1\"></span>        <span class=\"k\">private</span> <span class=\"k\">void</span> <span class=\"n\">button_Click</span><span class=\"p\">(</span><span class=\"kt\">object</span> <span class=\"n\">sender</span><span class=\"p\">,</span> <span class=\"n\">EventArgs</span> <span class=\"n\">e</span><span class=\"p\">)</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">excelName</span> <span class=\"p\">=</span> <span class=\"n\">textBox_fileName</span><span class=\"p\">.</span><span class=\"n\">Text</span><span class=\"p\">;</span>\n            <span class=\"n\">ExcelTools</span> <span class=\"n\">excel</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">ExcelTools</span><span class=\"p\">();</span>\n            <span class=\"n\">excel</span><span class=\"p\">.</span><span class=\"n\">OpenExcel</span><span class=\"p\">(</span><span class=\"n\">excelName</span><span class=\"p\">);</span><span class=\"c1\">//打开表格\n</span><span class=\"c1\"></span>            <span class=\"kt\">int</span> <span class=\"n\">sheetID</span> <span class=\"p\">=</span> <span class=\"n\">Convert</span><span class=\"p\">.</span><span class=\"n\">ToInt32</span><span class=\"p\">(</span><span class=\"n\">textBox_sheetName</span><span class=\"p\">.</span><span class=\"n\">Text</span><span class=\"p\">);</span>\n            <span class=\"kt\">int</span> <span class=\"n\">row</span> <span class=\"p\">=</span> <span class=\"n\">Convert</span><span class=\"p\">.</span><span class=\"n\">ToInt32</span><span class=\"p\">(</span><span class=\"n\">textBox_row</span><span class=\"p\">.</span><span class=\"n\">Text</span><span class=\"p\">);</span>\n            <span class=\"kt\">int</span> <span class=\"n\">col</span> <span class=\"p\">=</span> <span class=\"n\">Convert</span><span class=\"p\">.</span><span class=\"n\">ToInt32</span><span class=\"p\">(</span><span class=\"n\">textBox_col</span><span class=\"p\">.</span><span class=\"n\">Text</span><span class=\"p\">);</span>\n            <span class=\"n\">importData</span> <span class=\"p\">=</span> <span class=\"n\">excel</span><span class=\"p\">.</span><span class=\"n\">ReadCell</span><span class=\"p\">(</span><span class=\"n\">sheetID</span><span class=\"p\">,</span><span class=\"n\">row</span><span class=\"p\">,</span><span class=\"n\">col</span><span class=\"p\">);</span><span class=\"c1\">//读取单元格\n</span><span class=\"c1\"></span>            <span class=\"n\">excel</span><span class=\"p\">.</span><span class=\"n\">ColseExcel</span><span class=\"p\">();</span><span class=\"c1\">//关闭表格\n</span><span class=\"c1\"></span>            <span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">DialogResult</span> <span class=\"p\">=</span> <span class=\"n\">DialogResult</span><span class=\"p\">.</span><span class=\"n\">OK</span><span class=\"p\">;</span>\n            <span class=\"k\">this</span><span class=\"p\">.</span><span class=\"n\">Close</span><span class=\"p\">();</span>\n        <span class=\"p\">}</span>\n        \n       \n    <span class=\"p\">}</span>\n<span class=\"p\">}</span>\n</code></pre></div><p><b>&lt;备注1&gt;</b></p><p><b>CAD中加载窗体的方式</b></p><p><a href=\"https://link.zhihu.com/?target=http%3A//xn--cad-x68dk4d062i.net/\" class=\" wrap external\" target=\"_blank\" rel=\"nofollow noreferrer\">CAD中使用.NET</a> Form类的ShowDialog()函数来显示窗体会带来很多不可预料的错误。</p><p><a href=\"https://link.zhihu.com/?target=http%3A//autocad.net/\" class=\" wrap external\" target=\"_blank\" rel=\"nofollow noreferrer\">AutoCAD.NET</a> API提供了两个专门的函数用来替代ShowDialog()；</p><p>ShowModalDialog Method(Form)和Application.ShowModelessDialog (Form) </p><p>命名空间：Autodesk.AutoCAD.ApplicationServices </p><p>所属类：Application</p><p>public static System.Windows.Forms.DialogResult ShowModalDialog(Form formToShow);//模态方式，窗体和CAD间不能切换</p><p>public static void ShowModelessDialog(Form formToShow);//非模态方式，窗体和CAD间可任意切换</p><p>注意：非必须的情况下，应该使用模态方式，防止出现各类问题；</p>", 
            "topic": [
                {
                    "tag": "C#", 
                    "tagLink": "https://api.zhihu.com/topics/19590712"
                }
            ], 
            "comments": [
                {
                    "userName": "喵喵不吃鱼", 
                    "userLink": "https://www.zhihu.com/people/23f0105a60fe09c450392e6cde6d5f11", 
                    "content": "请问楼主能不能给帮忙这个代码，vs里新建类库，cad里输入相应指令，可以在cad里直接弹出九九乘法表😊万分感谢！", 
                    "likes": 0, 
                    "childComments": []
                }
            ]
        }, 
        {
            "url": "https://zhuanlan.zhihu.com/p/32434945", 
            "userName": "大非sb", 
            "userLink": "https://www.zhihu.com/people/9c5ffb79f07bb76c93142898396dcb04", 
            "upvote": 6, 
            "title": "AutoCAD.NET 二次开发--CAD中导入Excel数据", 
            "content": "<p><b>1、需求</b>：将Excel表格中的数据导入到CAD中，演示代码实现读取表格单元格的数据，然后在命令栏输出</p><p><b>2、思路</b>：用一个ExcelTools类，通过添加COM引用操作Excel表格，简单实现表格读取的功能；</p><p><b>3、环境</b>：AutoCAD 2008/Office 2010/vs2010</p><p><b>4、步骤</b>：</p><p><b>第一步</b>：新建ExcelTools类，添加COM引用：MicroSoft Excel 14.0 Ojbect Library(Excel 2010)</p><p><b>第二步</b>：引入命名空间：Microsoft.Office.Interop.Excel;</p><p><b>第三步</b>：实现三个简单方法：</p><p>public void   OpenExcel(string fileName) //打开表格</p><p>public string ReadCell(int sheetID, int row, int col)//根据工作簿的ID来读取单元格</p><p>public string ReadCell(string sheetName, int row, int col)//根据工作簿的名称来读取单元格</p><p>public void   ColseExcel()//关闭表格</p><p><b>第四步</b>：获取当前CAD文档的Editor命令栏，将读取的表格单元格数据输出到命令栏</p><p>具体代码如下：</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"c1\">//ExcelTools类代码\n</span><span class=\"c1\"></span><span class=\"k\">using</span> <span class=\"nn\">System</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Collections.Generic</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Linq</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Text</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Reflection</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Microsoft.Office.Interop.Excel</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">MyExcel</span> <span class=\"p\">=</span> <span class=\"n\">Microsoft</span><span class=\"p\">.</span><span class=\"n\">Office</span><span class=\"p\">.</span><span class=\"n\">Interop</span><span class=\"p\">.</span><span class=\"n\">Excel</span><span class=\"p\">;</span>\n\n<span class=\"k\">namespace</span> <span class=\"nn\">ImportExcelToCAD</span>\n<span class=\"p\">{</span>\n    <span class=\"k\">class</span> <span class=\"nc\">ExcelTools</span>\n    <span class=\"p\">{</span>\n        <span class=\"n\">MyExcel</span><span class=\"p\">.</span><span class=\"n\">Application</span> <span class=\"n\">excel</span><span class=\"p\">;</span>\n        <span class=\"n\">MyExcel</span><span class=\"p\">.</span><span class=\"n\">Workbook</span> <span class=\"n\">workbook</span><span class=\"p\">;</span>\n        <span class=\"n\">MyExcel</span><span class=\"p\">.</span><span class=\"n\">Worksheet</span> <span class=\"n\">worksheet</span><span class=\"p\">;</span>\n        <span class=\"kt\">object</span> <span class=\"n\">Nothing</span> <span class=\"p\">=</span> <span class=\"n\">Missing</span><span class=\"p\">.</span><span class=\"n\">Value</span><span class=\"p\">;</span>\n        <span class=\"c1\">/// &lt;summary&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// 打开工作簿\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;/summary&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;param name=&#34;fileName&#34;&gt;excel表格完整路径&lt;/param&gt;\n</span><span class=\"c1\"></span>        <span class=\"k\">public</span> <span class=\"k\">void</span> <span class=\"n\">OpenExcel</span><span class=\"p\">(</span><span class=\"kt\">string</span> <span class=\"n\">fileName</span><span class=\"p\">)</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">excel</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">MyExcel</span><span class=\"p\">.</span><span class=\"n\">Application</span><span class=\"p\">();</span>\n            <span class=\"n\">workbook</span> <span class=\"p\">=</span> <span class=\"n\">excel</span><span class=\"p\">.</span><span class=\"n\">Workbooks</span><span class=\"p\">.</span><span class=\"n\">Open</span><span class=\"p\">(</span><span class=\"n\">fileName</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span>\n                <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">);</span>\n        <span class=\"p\">}</span>\n        <span class=\"c1\">/// &lt;summary&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// 根据sheetID来读取指定的单元格\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;/summary&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;param name=&#34;sheetID&#34;&gt;&lt;/param&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;param name=&#34;row&#34;&gt;行&lt;/param&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;param name=&#34;col&#34;&gt;列&lt;/param&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;returns&gt;&lt;/returns&gt;\n</span><span class=\"c1\"></span>        <span class=\"k\">public</span> <span class=\"kt\">string</span> <span class=\"n\">ReadCell</span><span class=\"p\">(</span><span class=\"kt\">int</span> <span class=\"n\">sheetID</span><span class=\"p\">,</span> <span class=\"kt\">int</span> <span class=\"n\">row</span><span class=\"p\">,</span> <span class=\"kt\">int</span> <span class=\"n\">col</span><span class=\"p\">)</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">worksheet</span> <span class=\"p\">=</span> <span class=\"p\">(</span><span class=\"n\">Worksheet</span><span class=\"p\">)</span><span class=\"n\">workbook</span><span class=\"p\">.</span><span class=\"n\">Worksheets</span><span class=\"na\">[sheetID]</span><span class=\"p\">;</span>\n            <span class=\"kt\">string</span> <span class=\"k\">value</span> <span class=\"p\">=</span> <span class=\"p\">((</span><span class=\"n\">Range</span><span class=\"p\">)</span><span class=\"n\">worksheet</span><span class=\"p\">.</span><span class=\"n\">Cells</span><span class=\"na\">[row, col]</span><span class=\"p\">).</span><span class=\"n\">Text</span><span class=\"p\">.</span><span class=\"n\">ToString</span><span class=\"p\">();</span>\n            <span class=\"k\">return</span> <span class=\"k\">value</span><span class=\"p\">;</span>\n        <span class=\"p\">}</span>\n        <span class=\"c1\">//根据sheetName来读取指定的单元格\n</span><span class=\"c1\"></span>        <span class=\"k\">public</span> <span class=\"kt\">string</span> <span class=\"n\">ReadCell</span><span class=\"p\">(</span><span class=\"kt\">string</span> <span class=\"n\">sheetName</span><span class=\"p\">,</span> <span class=\"kt\">int</span> <span class=\"n\">row</span><span class=\"p\">,</span> <span class=\"kt\">int</span> <span class=\"n\">col</span><span class=\"p\">)</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">worksheet</span> <span class=\"p\">=</span> <span class=\"p\">(</span><span class=\"n\">Worksheet</span><span class=\"p\">)</span><span class=\"n\">workbook</span><span class=\"p\">.</span><span class=\"n\">Worksheets</span><span class=\"na\">[sheetName]</span><span class=\"p\">;</span>\n            <span class=\"kt\">string</span> <span class=\"k\">value</span> <span class=\"p\">=</span> <span class=\"p\">((</span><span class=\"n\">Range</span><span class=\"p\">)</span><span class=\"n\">worksheet</span><span class=\"p\">.</span><span class=\"n\">Cells</span><span class=\"na\">[row, col]</span><span class=\"p\">).</span><span class=\"n\">Text</span><span class=\"p\">.</span><span class=\"n\">ToString</span><span class=\"p\">();</span>\n            <span class=\"k\">return</span> <span class=\"k\">value</span><span class=\"p\">;</span>\n        <span class=\"p\">}</span>\n        <span class=\"c1\">//关闭表格\n</span><span class=\"c1\"></span>        <span class=\"k\">public</span> <span class=\"k\">void</span> <span class=\"n\">ColseExcel</span><span class=\"p\">()</span><span class=\"c1\">//关闭表格\n</span><span class=\"c1\"></span>        <span class=\"p\">{</span>\n            <span class=\"n\">workbook</span><span class=\"p\">.</span><span class=\"n\">Close</span><span class=\"p\">(</span><span class=\"k\">false</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">,</span> <span class=\"n\">Nothing</span><span class=\"p\">);</span>\n            <span class=\"n\">workbook</span> <span class=\"p\">=</span> <span class=\"k\">null</span><span class=\"p\">;</span>\n            <span class=\"n\">excel</span><span class=\"p\">.</span><span class=\"n\">Quit</span><span class=\"p\">();</span>\n            <span class=\"n\">excel</span> <span class=\"p\">=</span> <span class=\"k\">null</span><span class=\"p\">;</span>\n        <span class=\"p\">}</span>\n    <span class=\"p\">}</span>\n<span class=\"p\">}</span>\n\n<span class=\"c1\">//主程序代码\n</span><span class=\"c1\"></span><span class=\"k\">using</span> <span class=\"nn\">System</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Collections.Generic</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Linq</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Text</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.Runtime</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.ApplicationServices</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.EditorInput</span><span class=\"p\">;</span>\n\n<span class=\"k\">namespace</span> <span class=\"nn\">ImportExcelToCAD</span>\n<span class=\"p\">{</span>\n    <span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Class1</span>\n    <span class=\"p\">{</span><span class=\"na\">\n</span><span class=\"na\">        [CommandMethod(&#34;aaa&#34;)]</span>\n        <span class=\"k\">public</span> <span class=\"k\">void</span> <span class=\"n\">ImportExcelData</span><span class=\"p\">()</span>\n        <span class=\"p\">{</span>\n            <span class=\"kt\">string</span> <span class=\"n\">excelPath</span> <span class=\"p\">=</span> <span class=\"s\">@&#34;C:\\Users\\Administrator\\Desktop\\新建文件夹\\test.xlsx&#34;</span><span class=\"p\">;</span>  \n            <span class=\"n\">Document</span> <span class=\"n\">doc</span> <span class=\"p\">=</span> <span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">DocumentManager</span><span class=\"p\">.</span><span class=\"n\">MdiActiveDocument</span><span class=\"p\">;</span>\n            <span class=\"n\">Editor</span> <span class=\"n\">ed</span> <span class=\"p\">=</span> <span class=\"n\">doc</span><span class=\"p\">.</span><span class=\"n\">Editor</span><span class=\"p\">;</span>           \n            <span class=\"k\">try</span> \n            <span class=\"p\">{</span>\n                <span class=\"n\">ExcelTools</span> <span class=\"n\">tool</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">ExcelTools</span><span class=\"p\">();</span>\n                <span class=\"n\">tool</span><span class=\"p\">.</span><span class=\"n\">OpenExcel</span><span class=\"p\">(</span><span class=\"n\">excelPath</span><span class=\"p\">);</span><span class=\"c1\">//打开表格\n</span><span class=\"c1\"></span>                <span class=\"kt\">string</span> <span class=\"n\">data</span> <span class=\"p\">=</span> <span class=\"n\">tool</span><span class=\"p\">.</span><span class=\"n\">ReadCell</span><span class=\"p\">(</span><span class=\"s\">&#34;Sheet1&#34;</span><span class=\"p\">,</span> <span class=\"m\">1</span><span class=\"p\">,</span> <span class=\"m\">1</span><span class=\"p\">);</span><span class=\"c1\">//读取sheet1，第一行第一列单元格的值\n</span><span class=\"c1\"></span>                <span class=\"n\">tool</span><span class=\"p\">.</span><span class=\"n\">ColseExcel</span><span class=\"p\">();</span><span class=\"c1\">//关闭表格\n</span><span class=\"c1\"></span>                <span class=\"n\">ed</span><span class=\"p\">.</span><span class=\"n\">WriteMessage</span><span class=\"p\">(</span><span class=\"s\">&#34;从表格中读取的数据为：&#34;</span> <span class=\"p\">+</span> <span class=\"n\">data</span><span class=\"p\">);</span><span class=\"c1\">//在命令栏输出\n</span><span class=\"c1\"></span>            <span class=\"p\">}</span>\n            <span class=\"k\">catch</span><span class=\"p\">(</span><span class=\"n\">Autodesk</span><span class=\"p\">.</span><span class=\"n\">AutoCAD</span><span class=\"p\">.</span><span class=\"n\">Runtime</span><span class=\"p\">.</span><span class=\"n\">Exception</span> <span class=\"n\">ex</span><span class=\"p\">)</span>\n            <span class=\"p\">{</span>\n                <span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">ShowAlertDialog</span><span class=\"p\">(</span><span class=\"s\">&#34;错误：&#34;</span> <span class=\"p\">+</span> <span class=\"n\">ex</span><span class=\"p\">.</span><span class=\"n\">Message</span><span class=\"p\">);</span>\n            <span class=\"p\">}</span>                    \n        <span class=\"p\">}</span>\n    <span class=\"p\">}</span>\n<span class=\"p\">}</span>\n</code></pre></div><p><b>Excel操作知识点：</b></p><p>&lt;1&gt;</p><p><b>Workbooks.Open方法</b></p><p>Open(FileName, UpdateLinks, ReadOnly, Format, Password, WriteResPassword, IgnoreReadOnlyRecommended, </p><p>Origin, Delimiter, Editable, Notify, Converter, AddToMru, Local, CorruptLoad)</p><p><b>描述</b>：打开一个工作簿</p><p><b>参数</b>：一般只需要定义FileName参数，其他参数全部缺省，参数具体含义请参考MicroSoft Excel 开发者文档</p><p>&lt;2&gt;</p><p><b>Workbook.Close 方法</b></p><p>Close(SaveChanges, Filename, RouteWorkbook)</p><p><b>描述</b>：关闭工作簿</p><p><b>参数</b>：</p><p>SaveChanges：是否保存true/false</p><p>Filename：要保存的文件名</p><p>RouteWorkbook：是否发送工作簿。一般设置缺省</p><p></p>", 
            "topic": [
                {
                    "tag": "C#", 
                    "tagLink": "https://api.zhihu.com/topics/19590712"
                }
            ], 
            "comments": [
                {
                    "userName": "deeplycloud", 
                    "userLink": "https://www.zhihu.com/people/31ad8e95f15ee12b550cdc08022fdc5e", 
                    "content": "<p>写得不错。AUTOCAD二次开发对设计师很管用。</p>", 
                    "likes": 1, 
                    "childComments": []
                }, 
                {
                    "userName": "喵喵不吃鱼", 
                    "userLink": "https://www.zhihu.com/people/23f0105a60fe09c450392e6cde6d5f11", 
                    "content": "请问楼主能不能给帮忙这个代码，vs里新建类库，cad里输入相应指令，可以在cad里直接弹出九九乘法表😊万分感谢！", 
                    "likes": 0, 
                    "childComments": []
                }
            ]
        }, 
        {
            "url": "https://zhuanlan.zhihu.com/p/32393930", 
            "userName": "大非sb", 
            "userLink": "https://www.zhihu.com/people/9c5ffb79f07bb76c93142898396dcb04", 
            "upvote": 0, 
            "title": "AutoCAD.NET 二次开发--插入外部文件中的块", 
            "content": "<h2>1、需求</h2><p>插入外部文件中指定的块。</p><h2>2、思路</h2><p>将外部dwg文件加载到临时数据库中，把外部dwg文件中自定义的命名块复制到当前文档的数据库中；新建指定块的块参照加入到当前块表记录。</p><h2>3、环境</h2><p>AutoCAD 2008/vs2010</p><h2>4、步骤：</h2><p><b>(1) 新建一个临时图形数据库 </b></p><p>Database tempDB = new Database(false, true);</p><p><b>(2) 调用Database类的 WblockCloneObjects()方法复制块</b></p><p><b>(3) 新建一个块参照：BlockReference</b></p><p>public BlockReference(Point3d position,  ObjectId blockTableRecord);</p><p><b>(4) 把块参照添加到块表记录中</b></p><p>BlockTableRecord.AppendEntity()</p><p>Transaction.AddNewlyCreatedDBObject();</p><p class=\"ztext-empty-paragraph\"><br/></p><p><b>新建一个CADTools类，实现导入外部dwg文件中的自定义块</b></p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"k\">using</span> <span class=\"nn\">System</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Collections.Generic</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Linq</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Text</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.ApplicationServices</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.Runtime</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.DatabaseServices</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.EditorInput</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.Geometry</span><span class=\"p\">;</span>\n<span class=\"k\">namespace</span> <span class=\"nn\">InsertBlock</span>\n<span class=\"p\">{</span>\n    <span class=\"k\">class</span> <span class=\"nc\">CADTools</span>\n    <span class=\"p\">{</span>\n        <span class=\"c1\">/// &lt;summary&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// 导入外部dwg文件中自定义的块\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;/summary&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;param name=&#34;dwgFileName&#34;&gt;DWG文件路径&lt;/param&gt;\n</span><span class=\"c1\"></span>        <span class=\"c1\">/// &lt;param name=&#34;currentDB&#34;&gt;当前database&lt;/param&gt;\n</span><span class=\"c1\"></span>        <span class=\"k\">public</span> <span class=\"k\">static</span> <span class=\"k\">void</span> <span class=\"n\">ImportBlocksFromDWG</span><span class=\"p\">(</span><span class=\"kt\">string</span> <span class=\"n\">dwgFileName</span><span class=\"p\">,</span><span class=\"n\">Database</span> <span class=\"n\">currentDB</span><span class=\"p\">)</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">Database</span> <span class=\"n\">tempDB</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">Database</span><span class=\"p\">(</span><span class=\"k\">false</span><span class=\"p\">,</span> <span class=\"k\">true</span><span class=\"p\">);</span><span class=\"c1\">//新建一个临时图形数据库&lt;1&gt;\n</span><span class=\"c1\"></span>            <span class=\"k\">try</span>\n            <span class=\"p\">{</span>\n                <span class=\"n\">tempDB</span><span class=\"p\">.</span><span class=\"n\">ReadDwgFile</span><span class=\"p\">(</span><span class=\"n\">dwgFileName</span><span class=\"p\">,</span> <span class=\"n\">System</span><span class=\"p\">.</span><span class=\"n\">IO</span><span class=\"p\">.</span><span class=\"n\">FileShare</span><span class=\"p\">.</span><span class=\"n\">Read</span><span class=\"p\">,</span> <span class=\"k\">true</span><span class=\"p\">,</span> <span class=\"k\">null</span><span class=\"p\">);</span><span class=\"c1\">//读取外部DWG到临时数据库&lt;2&gt;\n</span><span class=\"c1\"></span>                <span class=\"n\">ObjectIdCollection</span> <span class=\"n\">ids</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">ObjectIdCollection</span><span class=\"p\">();</span><span class=\"c1\">//存放块OjbectId的集合\n</span><span class=\"c1\"></span>                <span class=\"k\">using</span> <span class=\"p\">(</span><span class=\"n\">Transaction</span> <span class=\"n\">trans</span> <span class=\"p\">=</span> <span class=\"n\">tempDB</span><span class=\"p\">.</span><span class=\"n\">TransactionManager</span><span class=\"p\">.</span><span class=\"n\">StartTransaction</span><span class=\"p\">())</span>\n                <span class=\"p\">{</span>\n                    <span class=\"n\">BlockTable</span> <span class=\"n\">bt</span> <span class=\"p\">=</span> <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">GetObject</span><span class=\"p\">(</span><span class=\"n\">tempDB</span><span class=\"p\">.</span><span class=\"n\">BlockTableId</span><span class=\"p\">,</span> <span class=\"n\">OpenMode</span><span class=\"p\">.</span><span class=\"n\">ForRead</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">BlockTable</span><span class=\"p\">;</span>\n                    <span class=\"k\">foreach</span> <span class=\"p\">(</span><span class=\"n\">ObjectId</span> <span class=\"n\">item</span> <span class=\"k\">in</span> <span class=\"n\">bt</span><span class=\"p\">)</span>\n                    <span class=\"p\">{</span>\n                        <span class=\"n\">BlockTableRecord</span> <span class=\"n\">btr</span> <span class=\"p\">=</span> <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">GetObject</span><span class=\"p\">(</span><span class=\"n\">item</span><span class=\"p\">,</span> <span class=\"n\">OpenMode</span><span class=\"p\">.</span><span class=\"n\">ForRead</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">BlockTableRecord</span><span class=\"p\">;</span>\n                        <span class=\"k\">if</span> <span class=\"p\">(!</span><span class=\"n\">btr</span><span class=\"p\">.</span><span class=\"n\">IsAnonymous</span> <span class=\"p\">&amp;&amp;</span> <span class=\"p\">!</span><span class=\"n\">btr</span><span class=\"p\">.</span><span class=\"n\">IsLayout</span><span class=\"p\">)</span><span class=\"c1\">//筛选自定义的命名块,剔除匿名块和布局块\n</span><span class=\"c1\"></span>                        <span class=\"p\">{</span>\n                            <span class=\"n\">ids</span><span class=\"p\">.</span><span class=\"n\">Add</span><span class=\"p\">(</span><span class=\"n\">item</span><span class=\"p\">);</span>\n                        <span class=\"p\">}</span>\n                    <span class=\"p\">}</span>\n                <span class=\"p\">}</span>\n                    <span class=\"c1\">//复制临时数据库中的块到当前数据库的块表中&lt;3&gt;       \n</span><span class=\"c1\"></span>                    <span class=\"n\">tempDB</span><span class=\"p\">.</span><span class=\"n\">WblockCloneObjects</span><span class=\"p\">(</span><span class=\"n\">ids</span><span class=\"p\">,</span> <span class=\"n\">currentDB</span><span class=\"p\">.</span><span class=\"n\">BlockTableId</span><span class=\"p\">,</span> <span class=\"k\">new</span> <span class=\"n\">IdMapping</span><span class=\"p\">(),</span> <span class=\"n\">DuplicateRecordCloning</span><span class=\"p\">.</span><span class=\"n\">Replace</span><span class=\"p\">,</span> <span class=\"k\">false</span><span class=\"p\">);</span>\n            <span class=\"p\">}</span>\n            <span class=\"k\">catch</span> <span class=\"p\">(</span><span class=\"n\">Autodesk</span><span class=\"p\">.</span><span class=\"n\">AutoCAD</span><span class=\"p\">.</span><span class=\"n\">Runtime</span><span class=\"p\">.</span><span class=\"n\">Exception</span> <span class=\"n\">ex</span><span class=\"p\">)</span>\n            <span class=\"p\">{</span>\n                <span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">ShowAlertDialog</span><span class=\"p\">(</span><span class=\"s\">&#34;错误：&#34;</span><span class=\"p\">+</span><span class=\"n\">ex</span><span class=\"p\">.</span><span class=\"n\">Message</span><span class=\"p\">);</span>\n            <span class=\"p\">}</span>      \n            <span class=\"n\">tempDB</span><span class=\"p\">.</span><span class=\"n\">Dispose</span><span class=\"p\">();</span>\n        <span class=\"p\">}</span>\n    <span class=\"p\">}</span>\n<span class=\"p\">}</span>\n</code></pre></div><p><b>主程序代码：</b></p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"p\">/</span><span class=\"err\">插入外部文件中指定的块</span>\n<span class=\"k\">using</span> <span class=\"nn\">System</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Collections.Generic</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Linq</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">System.Text</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.ApplicationServices</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.Runtime</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.DatabaseServices</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.EditorInput</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.Geometry</span><span class=\"p\">;</span>\n\n<span class=\"k\">namespace</span> <span class=\"nn\">InsertBlock</span>\n<span class=\"p\">{</span>\n    <span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Class1</span>       \n    <span class=\"p\">{</span><span class=\"na\">\n</span><span class=\"na\">        [CommandMethod(&#34;ib&#34;)]</span>\n        <span class=\"k\">public</span> <span class=\"k\">void</span> <span class=\"n\">InsertBlock</span><span class=\"p\">()</span>\n        <span class=\"p\">{</span>\n            <span class=\"kt\">string</span> <span class=\"n\">fileName</span><span class=\"p\">=</span><span class=\"s\">@&#34;F:\\备份\\CAD插件\\工作块\\block.dwg&#34;</span><span class=\"p\">;</span>  <span class=\"c1\">//外部dwg文件的完整路径   、\n</span><span class=\"c1\"></span>            <span class=\"kt\">string</span> <span class=\"n\">insertBlockName</span> <span class=\"p\">=</span> <span class=\"s\">&#34;block1&#34;</span><span class=\"p\">;</span><span class=\"c1\">//要插入的块名\n</span><span class=\"c1\"></span>            <span class=\"n\">Document</span> <span class=\"n\">doc</span> <span class=\"p\">=</span> <span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">DocumentManager</span><span class=\"p\">.</span><span class=\"n\">MdiActiveDocument</span><span class=\"p\">;</span>\n            <span class=\"n\">Database</span> <span class=\"n\">db</span> <span class=\"p\">=</span> <span class=\"n\">doc</span><span class=\"p\">.</span><span class=\"n\">Database</span><span class=\"p\">;</span>\n            <span class=\"n\">Editor</span> <span class=\"n\">ed</span> <span class=\"p\">=</span> <span class=\"n\">doc</span><span class=\"p\">.</span><span class=\"n\">Editor</span><span class=\"p\">;</span>\n            <span class=\"n\">PromptPointResult</span> <span class=\"n\">getPoint</span> <span class=\"p\">=</span> <span class=\"n\">ed</span><span class=\"p\">.</span><span class=\"n\">GetPoint</span><span class=\"p\">(</span><span class=\"s\">&#34;请选择插入点&#34;</span><span class=\"p\">);</span>\n            <span class=\"n\">Point3d</span> <span class=\"n\">p</span> <span class=\"p\">=</span> <span class=\"n\">getPoint</span><span class=\"p\">.</span><span class=\"n\">Value</span><span class=\"p\">;</span>\n            <span class=\"n\">CADTools</span><span class=\"p\">.</span><span class=\"n\">ImportBlocksFromDWG</span><span class=\"p\">(</span><span class=\"n\">fileName</span><span class=\"p\">,</span><span class=\"n\">db</span><span class=\"p\">);</span> <span class=\"c1\">//导入外部文件中的块           \n</span><span class=\"c1\"></span>            <span class=\"k\">using</span> <span class=\"p\">(</span><span class=\"n\">Transaction</span> <span class=\"n\">trans</span> <span class=\"p\">=</span> <span class=\"n\">db</span><span class=\"p\">.</span><span class=\"n\">TransactionManager</span><span class=\"p\">.</span><span class=\"n\">StartTransaction</span><span class=\"p\">())</span>\n            <span class=\"p\">{</span>\n                <span class=\"n\">BlockTable</span> <span class=\"n\">bt</span> <span class=\"p\">=</span> <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">GetObject</span><span class=\"p\">(</span><span class=\"n\">db</span><span class=\"p\">.</span><span class=\"n\">BlockTableId</span><span class=\"p\">,</span> <span class=\"n\">OpenMode</span><span class=\"p\">.</span><span class=\"n\">ForRead</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">BlockTable</span><span class=\"p\">;</span>\n                <span class=\"n\">BlockTableRecord</span> <span class=\"n\">btr</span> <span class=\"p\">=</span> <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">GetObject</span><span class=\"p\">(</span><span class=\"n\">bt</span><span class=\"na\">[BlockTableRecord.ModelSpace]</span><span class=\"p\">,</span><span class=\"n\">OpenMode</span><span class=\"p\">.</span><span class=\"n\">ForWrite</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">BlockTableRecord</span><span class=\"p\">;</span>\n                <span class=\"k\">using</span> <span class=\"p\">(</span><span class=\"n\">BlockReference</span> <span class=\"n\">brf</span> <span class=\"p\">=</span> <span class=\"k\">new</span> <span class=\"n\">BlockReference</span><span class=\"p\">(</span><span class=\"n\">p</span><span class=\"p\">,</span> <span class=\"n\">bt</span><span class=\"na\">[insertBlockName]</span><span class=\"p\">))</span><span class=\"c1\">//插入块&lt;4&gt;\n</span><span class=\"c1\"></span>                <span class=\"p\">{</span>\n                    <span class=\"n\">btr</span><span class=\"p\">.</span><span class=\"n\">AppendEntity</span><span class=\"p\">(</span><span class=\"n\">brf</span><span class=\"p\">);</span>\n                    <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">AddNewlyCreatedDBObject</span><span class=\"p\">(</span><span class=\"n\">brf</span><span class=\"p\">,</span><span class=\"k\">true</span><span class=\"p\">);</span>   \n                <span class=\"p\">}</span>\n                <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">Commit</span><span class=\"p\">();</span>\n            <span class=\"p\">}</span>               \n        <span class=\"p\">}</span>\n    <span class=\"p\">}</span>\n</code></pre></div><p><b>相关知识点说明：</b></p><p>&lt;1&gt;</p><p>public Database(bool buildDefaultDrawing, bool noDocument);</p><p>描述:</p><p>Database的构造函数</p><p>参数：</p><p>buildDefaultDrawing ：true-为生成的数据库添加基本数据（如基本的符号表等）；flase-空数据库</p><p>noDocument：true-创建的数据库不关联到当前文档；false-关联</p><p>&lt;2&gt;</p><p>public void ReadDwgFile(IntPtr drawingFile, FileOpenMode mode, bool allowCPConversion,  string password);</p><p>描述：读取DWG文件</p><p>参数：</p><p>drawingFile：文件完整路径名</p><p>mode：枚举类型Read,ReadWrite,Write</p><p>allowCPConversion：true-直接转换编码，false-弹出对话框提示</p><p>password：dwg文件的密码，没有则为null;</p><p class=\"ztext-empty-paragraph\"><br/></p><p>&lt;3&gt;</p><p>public void WblockCloneObjects(</p><p>   ObjectIdCollection identifiers, </p><p>   ObjectId id, 《</p><p>   IdMapping mapping, </p><p>   DuplicateRecordCloning cloning, </p><p>   bool deferTranslation</p><p>);</p><p>描述：将外部文件的块复制到当前数据库</p><p>参数：</p><p>identifiers：外部文件中块的ObjectId的集合</p><p>id：块复制的目标点（如当前数据库的块表）</p><p>mapping：源对象和复制对象的对应关系</p><p>cloning：有相同对象名时的复制方式 Ignore 忽略 ；Replace 替换</p><p>deferTranslation：是否进行ID转移，一般设置为 false</p><p>&lt;4&gt;</p><p>public BlockReference(Point3d position,  ObjectId blockTableRecord);</p><p>描述:块参照的构造函数;块参照可以简单理解为块定义的实现，也就是在文档中插入的块；块参照的操作和普通实体一样；</p><p>参数：</p><p>position：插入点</p><p>blockTableRecord：块的ObjectId</p><p>&lt;获取插入点&gt;</p><p>PromptPointResult getPoint = ed.GetPoint(&#34;请选择插入点&#34;);</p><p>Point3d p = getPoint.Value;</p>", 
            "topic": [
                {
                    "tag": "C#", 
                    "tagLink": "https://api.zhihu.com/topics/19590712"
                }
            ], 
            "comments": []
        }, 
        {
            "url": "https://zhuanlan.zhihu.com/p/32346882", 
            "userName": "大非sb", 
            "userLink": "https://www.zhihu.com/people/9c5ffb79f07bb76c93142898396dcb04", 
            "upvote": 1, 
            "title": "AutoCAD.NET 二次开发--获取指定类型的实体（实现文本的批量替换）", 
            "content": "<p><b>1、需求：</b>获取一个cad文档的所有单行文本。（以此实现文本的批量替换）</p><p><b>2、思路：</b>遍历模型空间块表记录的所有实体，判定其类型，如果是DBText，则在命令栏中输出DBText的文本内容。(稍作修改即可实现批量替换)</p><p><b>3、环境：</b>AutoCAD 2008，VS 2010</p><p><b>4、步骤：</b></p><p>1)：新建一个类库，NetFramework 框架选择3.5,添加AutoCAD 2008的两个dll引用：acmgd.dll，acdbmgd.dll。（在安装目录下能找到）</p><p>2)：添加命名空间</p><p>Autodesk.AutoCAD.ApplicationServices; //CAD实体</p><p>Autodesk.AutoCAD.EditorInput;//命令栏</p><p>Autodesk.AutoCAD.Runtime;//运行时，如设置 指令</p><p>Autodesk.AutoCAD.DatabaseServices;//数据库服务</p><p>3) 获取当前文档，数据库，和命令栏</p><p>4) 启一个事务，获取模型空间的所有块表记录；</p><p>5) 遍历块表记录的所有对象，判定是否为单行文本，如果是则在命令栏输出文本内容。</p><p>6) 编译和运行</p><p> 打开CAD，输入netload 加载编译的dll，输入指令：sss，即可看到运行效果</p><div class=\"highlight\"><pre><code class=\"language-csharp\"><span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.ApplicationServices</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.EditorInput</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.Runtime</span><span class=\"p\">;</span>\n<span class=\"k\">using</span> <span class=\"nn\">Autodesk.AutoCAD.DatabaseServices</span><span class=\"p\">;</span>\n<span class=\"k\">namespace</span> <span class=\"nn\">HelloWord</span>\n<span class=\"p\">{</span>\n    <span class=\"k\">public</span> <span class=\"k\">class</span> <span class=\"nc\">Class1</span>\n    <span class=\"p\">{</span><span class=\"na\">\n</span><span class=\"na\">        [CommandMethod(&#34;sss&#34;)]</span>\n        <span class=\"k\">public</span> <span class=\"k\">void</span> <span class=\"n\">Hello</span><span class=\"p\">()</span>\n        <span class=\"p\">{</span>\n            <span class=\"n\">Document</span> <span class=\"n\">doc</span> <span class=\"p\">=</span> <span class=\"n\">Application</span><span class=\"p\">.</span><span class=\"n\">DocumentManager</span><span class=\"p\">.</span><span class=\"n\">MdiActiveDocument</span><span class=\"p\">;</span><span class=\"c1\">//获取当前文档\n</span><span class=\"c1\"></span>            <span class=\"n\">Database</span> <span class=\"n\">db</span> <span class=\"p\">=</span> <span class=\"n\">doc</span><span class=\"p\">.</span><span class=\"n\">Database</span><span class=\"p\">;</span><span class=\"c1\">//获取当前数据库\n</span><span class=\"c1\"></span>            <span class=\"n\">Editor</span> <span class=\"n\">ed</span><span class=\"p\">=</span><span class=\"n\">doc</span><span class=\"p\">.</span><span class=\"n\">Editor</span><span class=\"p\">;</span><span class=\"c1\">//获取命令栏\n</span><span class=\"c1\"></span>            <span class=\"n\">using</span><span class=\"p\">(</span><span class=\"n\">Transaction</span> <span class=\"n\">trans</span><span class=\"p\">=</span><span class=\"n\">db</span><span class=\"p\">.</span><span class=\"n\">TransactionManager</span><span class=\"p\">.</span><span class=\"n\">StartTransaction</span><span class=\"p\">())</span><span class=\"c1\">//开启事务\n</span><span class=\"c1\"></span>            <span class=\"p\">{</span>\n                <span class=\"n\">BlockTable</span> <span class=\"n\">bt</span> <span class=\"p\">=</span> <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">GetObject</span><span class=\"p\">(</span><span class=\"n\">db</span><span class=\"p\">.</span><span class=\"n\">BlockTableId</span><span class=\"p\">,</span><span class=\"n\">OpenMode</span><span class=\"p\">.</span><span class=\"n\">ForRead</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">BlockTable</span><span class=\"p\">;</span><span class=\"c1\">//获取块表\n</span><span class=\"c1\"></span>                <span class=\"n\">BlockTableRecord</span> <span class=\"n\">btr</span> <span class=\"p\">=</span> <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">GetObject</span><span class=\"p\">(</span><span class=\"n\">bt</span><span class=\"na\">[BlockTableRecord.ModelSpace]</span><span class=\"p\">,</span><span class=\"n\">OpenMode</span><span class=\"p\">.</span><span class=\"n\">ForRead</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">BlockTableRecord</span><span class=\"p\">;</span><span class=\"c1\">//获取模型空间的块表记录\n</span><span class=\"c1\"></span>                <span class=\"n\">ed</span><span class=\"p\">.</span><span class=\"n\">WriteMessage</span><span class=\"p\">(</span><span class=\"s\">&#34;\\n罗列所有单行文本：&#34;</span><span class=\"p\">);</span>               \n                <span class=\"k\">foreach</span> <span class=\"p\">(</span><span class=\"n\">ObjectId</span> <span class=\"n\">item</span> <span class=\"k\">in</span> <span class=\"n\">btr</span><span class=\"p\">)</span>\n                <span class=\"p\">{</span>\n                    <span class=\"n\">Entity</span> <span class=\"n\">ent</span> <span class=\"p\">=</span> <span class=\"n\">trans</span><span class=\"p\">.</span><span class=\"n\">GetObject</span><span class=\"p\">(</span><span class=\"n\">item</span><span class=\"p\">,</span><span class=\"n\">OpenMode</span><span class=\"p\">.</span><span class=\"n\">ForRead</span><span class=\"p\">)</span> <span class=\"k\">as</span> <span class=\"n\">Entity</span><span class=\"p\">;</span>\n                    <span class=\"k\">if</span><span class=\"p\">(</span><span class=\"n\">ent</span><span class=\"p\">.</span><span class=\"n\">GetType</span><span class=\"p\">()==</span><span class=\"k\">typeof</span><span class=\"p\">(</span><span class=\"n\">DBText</span><span class=\"p\">))</span><span class=\"c1\">//判定是否为单行文本\n</span><span class=\"c1\"></span>                    <span class=\"p\">{</span>\n                        <span class=\"n\">DBText</span> <span class=\"n\">text</span><span class=\"p\">=</span><span class=\"n\">ent</span> <span class=\"k\">as</span> <span class=\"n\">DBText</span><span class=\"p\">;</span>\n                        <span class=\"n\">ed</span><span class=\"p\">.</span><span class=\"n\">WriteMessage</span><span class=\"p\">(</span><span class=\"s\">&#34;\\n&#34;</span><span class=\"p\">+</span><span class=\"n\">text</span><span class=\"p\">.</span><span class=\"n\">TextString</span><span class=\"p\">);</span>\n                    <span class=\"p\">}</span>                   \n                <span class=\"p\">}</span>\n            <span class=\"p\">}</span>            \n        <span class=\"p\">}</span>\n    <span class=\"p\">}</span>\n<span class=\"p\">}</span>\n</code></pre></div><p></p>", 
            "topic": [
                {
                    "tag": "C#", 
                    "tagLink": "https://api.zhihu.com/topics/19590712"
                }
            ], 
            "comments": []
        }
    ], 
    "url": "https://zhuanlan.zhihu.com/c_147277590"
}
